In [1]:
#Импортируем библиотку для работы
import pandas as pd

In [2]:
#Читаем первый лист
df=pd.read_excel(r'C:\Users\Paul\Documents\ГКУ МЦРСТ\Python.xlsx',sheet_name='Прикрепленное население')

In [3]:
#Смотрим информацию о листе
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Округ                             347 non-null    object
 1   Наименование поликлиники          347 non-null    object
 2   Наименование филиала              347 non-null    object
 3   Прикрепленное население на 01.07  347 non-null    int64
 4   Прикрепленное население на 01.08  347 non-null    int64
 5   Прикрепленное население на 01.09  347 non-null    int64
dtypes: int64(3), object(3)
memory usage: 16.4+ KB
None

Сформируем первые две требуемые таблицы

In [4]:
#Формируем сводную таблицу в разбивке по округам и считаем количество прикрепленного населения по месяцам
table_1_1=df.groupby(['Округ']).agg({'Прикрепленное население на 01.07':sum,
                           'Прикрепленное население на 01.08':sum,
                           'Прикрепленное население на 01.09':sum}).copy()
table_1_1

,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прикрепленное население на 01.09
Округ,,,
Округ 1,1374841,1376032,1378397
Округ 2,1239533,1242264,1247440
Округ 3,2574811,2578452,2585511
Округ 4,1259254,1261734,1265705
Округ 5,992555,995001,999263
Округ 6,625641,626190,628149
Округ 8,1064288,1064325,1066234
Округ 9,1377705,1379270,1381464

In [5]:
#Формируем две колонки с приростом приклепения населения в процентах с округлением до двух знаков после запятой
col_1= list(
    round(
        ((table_1_1['Прикрепленное население на 01.08']-table_1_1['Прикрепленное население на 01.07'])/
         table_1_1['Прикрепленное население на 01.07']).mul(100),2)
)
col_2= list(
    round(
        ((table_1_1['Прикрепленное население на 01.09']-table_1_1['Прикрепленное население на 01.08'])/
         table_1_1['Прикрепленное население на 01.08']).mul(100),2)
)

In [6]:
#Добавляем новые столбцы
table_1_1.insert(2, "Прирост в % июль-август", col_1)
table_1_1.insert(4, "Прирост в % август-сентябрь", col_2)
table_1_1

,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прирост в % июль-август,Прикрепленное население на 01.09,Прирост в % август-сентябрь
Округ,,,,,
Округ 1,1374841,1376032,0.09,1378397,0.17
Округ 2,1239533,1242264,0.22,1247440,0.42
Округ 3,2574811,2578452,0.14,2585511,0.27
Округ 4,1259254,1261734,0.20,1265705,0.31
Округ 5,992555,995001,0.25,999263,0.43
Округ 6,625641,626190,0.09,628149,0.31
Округ 8,1064288,1064325,0.00,1066234,0.18
Округ 9,1377705,1379270,0.11,1381464,0.16

In [7]:
#Читаем второй лист, чтобы составить вторую таблицу с рейтингом специальностей по количеству приемов в сентябре
df2=pd.read_excel(r'C:\Users\Paul\Documents\ГКУ МЦРСТ\Python.xlsx',sheet_name='Структура записей и приемов')

In [8]:
#Смотрим информацию о листе
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 19 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Округ                                                1389 non-null   object
 1   Тип организации                                      1389 non-null   object
 2   Обслуживаемое население                              1389 non-null   object
 3   Наименование поликлиники                             1389 non-null   object
 4   Наименование филиала                                 1389 non-null   object
 5   Специальность врача                                  1389 non-null   object
 6   Группа специальностей                                1389 non-null   object
 7   Количество записей (Июль)                            1389 non-null   float64
 8   Количество состоявшихся приемов, в т. ч. (Июль)      1389 non-null   float64
 9   количество плановых приемов (Июль)                   1389 non-null   float64
 10  количество внеплановых приемов (Июль)                1389 non-null   float64
 11  Количество записей (Август)                          1389 non-null   float64
 12  Количество состоявшихся приемов, в т. ч. (Август)    1389 non-null   float64
 13  количество плановых приемов (Август)                 1389 non-null   float64
 14  количество внеплановых приемов (Август)              1389 non-null   float64
 15  Количество записей (Сентябрь)                        1389 non-null   float64
 16  Количество состоявшихся приемов, в т. ч. (Сентябрь)  1389 non-null   float64
 17  количество плановых приемов (Сентябрь)               1389 non-null   float64
 18  количество внеплановых приемов (Сентябрь)            1389 non-null   float64
dtypes: float64(12), object(7)
memory usage: 206.5+ KB

Сформируем вторую таблицу

In [9]:
#Делаем сводную таблицу специальностей врачей по количеству приемов в сентябре. Сортировку задаём от большего к меньшему.
table_1_2=df2.groupby('Специальность врача').agg({'Количество состоявшихся приемов, в т. ч. (Сентябрь)':sum}).astype('Int64')
table_1_2=table_1_2.sort_values(by='Количество состоявшихся приемов, в т. ч. (Сентябрь)',ascending=False)
table_1_2

                        Количество состоявшихся приемов, в т. ч. (Сентябрь)
Специальность врача
Врач-хирург                                                        186458
Врач-офтальмолог                                                   150395
Врач-оториноларинголог                                             114769
Врач-невролог                                                      112455
Врач-эндокринолог                                                  109307
Врач-уролог                                                        102119
Врач-кардиолог                                                      72523

Формируем третью таблицу

In [10]:
#Читаем третий лист
df3=pd.read_excel(r'C:\Users\Paul\Documents\ГКУ МЦРСТ\Python.xlsx',sheet_name='Количество ставок')

In [11]:
#Смотрим информацию о листе
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Округ                                         315 non-null    object
 1   Тип организации                               315 non-null    object
 2   Обслуживаемое население                       315 non-null    object
 3   Наименование поликлиники                      315 non-null    object
 4   Специальность врача                           315 non-null    object
 5   Группа специальностей                         315 non-null    object
 6   Количество ставок по состоянию на 01.07.2021  315 non-null    float64
 7   Количество ставок по состоянию на 01.08.2021  315 non-null    float64
 8   Количество ставок по состоянию на 01.09.2021  315 non-null    float64
dtypes: float64(3), object(6)
memory usage: 22.3+ KB

In [12]:
#Сделаем первые три колонки
table_3=df2.groupby(['Округ','Наименование поликлиники'])['Количество состоявшихся приемов, в т. ч. (Сентябрь)'].sum().reset_index()
table_3['Количество состоявшихся приемов, в т. ч. (Сентябрь)']=table_3['Количество состоявшихся приемов, в т. ч. (Сентябрь)'].astype('int64')
table_3.head(5)

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)"
0,Округ 1,Городская поликлиника № 17,18542
1,Округ 1,Городская поликлиника № 19,23479
2,Округ 1,Городская поликлиника № 31,21736
3,Округ 1,Городская поликлиника № 33,20768
4,Округ 1,Городская поликлиника № 35,19395

In [13]:
#Добавим колонку с долей внеплановых посещений
col_vneplan=list(
    round((df2.groupby(['Округ','Наименование поликлиники'])['количество внеплановых приемов (Сентябрь)'].sum()/
    df2.groupby(['Округ','Наименование поликлиники'])['Количество состоявшихся приемов, в т. ч. (Сентябрь)'].sum()).
                mul(100),2)
)
table_3['Доля внеплановых в %']=col_vneplan
table_3.head(5)

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)",Доля внеплановых в %
0,Округ 1,Городская поликлиника № 17,18542,5.48
1,Округ 1,Городская поликлиника № 19,23479,8.83
2,Округ 1,Городская поликлиника № 31,21736,4.92
3,Округ 1,Городская поликлиника № 33,20768,5.22
4,Округ 1,Городская поликлиника № 35,19395,11.82

In [14]:
#Добавим колонку с долей несостоявшихся плановых посещений
col_nesost=list(round(
    ((df2.groupby(['Округ','Наименование поликлиники'])['Количество записей (Сентябрь) '].sum()-
     df2.groupby(['Округ','Наименование поликлиники'])['количество плановых приемов (Сентябрь)'].sum())/
    df2.groupby(['Округ','Наименование поликлиники'])['Количество записей (Сентябрь) '].sum()).
                mul(100),2
))
table_3['Доля несост. план. %']=col_nesost
table_3.head(5)

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)",Доля внеплановых в %,Доля несост. план. %
0,Округ 1,Городская поликлиника № 17,18542,5.48,13.87
1,Округ 1,Городская поликлиника № 19,23479,8.83,6.75
2,Округ 1,Городская поликлиника № 31,21736,4.92,13.51
3,Округ 1,Городская поликлиника № 33,20768,5.22,8.04
4,Округ 1,Городская поликлиника № 35,19395,11.82,10.95

Была обнаружена проблема в наименовании поликлини Городская поликлиника № 37 (лишний пробел в конце строки)

In [15]:
df[df['Наименование поликлиники']=='Городская поликлиника № 37']

,Округ,Наименование поликлиники,Наименование филиала,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прикрепленное население на 01.09
73,Округ 2,Городская поликлиника № 37,Городская поликлиника № 37 филиал № 3,47356,47349,47441

In [16]:
#Удаляем на первом листе лишние пробелы возле строки Городская поликлиника № 37
df['Наименование поликлиники'] = df['Наименование поликлиники'].map(str.strip)

In [17]:
#Проверка
df[df['Наименование поликлиники']=='Городская поликлиника № 37']

,Округ,Наименование поликлиники,Наименование филиала,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прикрепленное население на 01.09
61,Округ 2,Городская поликлиника № 37,Городская поликлиника № 37,49494,49793,50268
73,Округ 2,Городская поликлиника № 37,Городская поликлиника № 37 филиал № 3,47356,47349,47441
110,Округ 2,Городская поликлиника № 37,Городская поликлиника № 37 филиал № 1,42211,42263,42342
122,Округ 2,Городская поликлиника № 37,Городская поликлиника № 37 филиал № 2,39895,39946,40126

In [18]:
#Создадим таблицу с первого листа, убрав детские поликлиники
discard = ["Детская"]
df_vzros= df[~df['Наименование поликлиники'].str.contains('|'.join(discard ))]
df_vzros

,Округ,Наименование поликлиники,Наименование филиала,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прикрепленное население на 01.09
0,Округ 2,Городская поликлиника № 3,Городская поликлиника № 3,92598,92829,93074
1,Округ 3,Городская поликлиника № 11,Городская поликлиника № 11,82299,82189,82076
2,Округ 1,Городская поликлиника № 35,Городская поликлиника № 35,81078,81307,81750
3,Округ 3,Городская поликлиника № 23,Городская поликлиника № 23,80338,80488,80811
4,Округ 3,Городская поликлиника № 23,Городская поликлиника № 23 филиал № 1,78026,78083,78262
...,...,...,...,...,...,...
278,Округ 4,Городская поликлиника № 42,Городская поликлиника № 42 филиал № 1,10837,10783,10734
293,Округ 2,Городская поликлиника № 3,Городская поликлиника № 3 филиал № 1,9907,9914,9929
300,Округ 9,Городская поликлиника № 46,Городская поликлиника № 46 филиал № 8,8931,9230,9600
318,Округ 6,Городская поликлиника № 25,Городская поликлиника № 25 филиал № 2,8067,8283,8464
345,Округ 3,Городская поликлиника № 30,Городская поликлиника № 30 филиал № 5,1807,1825,1827

In [19]:
#Добавим колонку с количеством прикрепленных на 01.09
col_prikrep=list(
    df_vzros.groupby(['Округ','Наименование поликлиники'])['Прикрепленное население на 01.09'].sum()   
)
table_3['Прикреп. 01.09']=col_prikrep
table_3.head(5)

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)",Доля внеплановых в %,Доля несост. план. %,Прикреп. 01.09
0,Округ 1,Городская поликлиника № 17,18542,5.48,13.87,207580
1,Округ 1,Городская поликлиника № 19,23479,8.83,6.75,232820
2,Округ 1,Городская поликлиника № 31,21736,4.92,13.51,193239
3,Округ 1,Городская поликлиника № 33,20768,5.22,8.04,219393
4,Округ 1,Городская поликлиника № 35,19395,11.82,10.95,181032

In [20]:
#Добавим колонку с количеством ставок на 01.09
df3.reset_index(drop=True)
col_stavok=list(
    df3.groupby(['Округ','Наименование поликлиники'])['Количество ставок по состоянию на 01.09.2021'].sum()   
)
col_stavok.insert(29, 0)
table_3['Ставок 01.09']=col_stavok
table_3.head(5)

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)",Доля внеплановых в %,Доля несост. план. %,Прикреп. 01.09,Ставок 01.09
0,Округ 1,Городская поликлиника № 17,18542,5.48,13.87,207580,57.50
1,Округ 1,Городская поликлиника № 19,23479,8.83,6.75,232820,46.25
2,Округ 1,Городская поликлиника № 31,21736,4.92,13.51,193239,53.25
3,Округ 1,Городская поликлиника № 33,20768,5.22,8.04,219393,43.25
4,Округ 1,Городская поликлиника № 35,19395,11.82,10.95,181032,41.50

Сформируем четвёртую таблицу

In [21]:
# Сформируем первые три столбца
table_4=df_vzros.groupby(['Округ','Наименование поликлиники'])['Прикрепленное население на 01.08'].sum().reset_index()
table_4['Прикрепленное население на 01.08']=table_4['Прикрепленное население на 01.08'].astype('int64')
table_4.head(5)

     Округ    Наименование поликлиники  Прикрепленное население на 01.08
0  Округ 1  Городская поликлиника № 17                            208546
1  Округ 1  Городская поликлиника № 19                            232064
2  Округ 1  Городская поликлиника № 31                            192351
3  Округ 1  Городская поликлиника № 33                            218461
4  Округ 1  Городская поликлиника № 35                            180347

In [22]:
#Добавим колонку состоявишхся приёмов врача-невролога на 01.08
col_nev=list(df2[df2['Специальность врача']=='Врач-невролог'].groupby(
 ['Округ','Наименование поликлиники']   
)['Количество состоявшихся приемов, в т. ч. (Август) '].sum())
table_4['col_priemov_nevrolog']=col_nev
table_4['col_priemov_nevrolog']=table_4['col_priemov_nevrolog'].astype('int64')
table_4.head(5)

,Округ,Наименование поликлиники,Прикрепленное население на 01.08,col_priemov_nevrolog
0,Округ 1,Городская поликлиника № 17,208546,1934
1,Округ 1,Городская поликлиника № 19,232064,3190
2,Округ 1,Городская поликлиника № 31,192351,3213
3,Округ 1,Городская поликлиника № 33,218461,2630
4,Округ 1,Городская поликлиника № 35,180347,1502

In [23]:
#Добавим колонку со ставкой врача-невролога на 01.08
col_nev_stav=list(round(df3[df3['Специальность врача']=='Врач-невролог'].groupby(
 ['Округ','Наименование поликлиники']   
)['Количество ставок по состоянию на 01.08.2021'].sum(),2))
col_nev_stav.insert(29, 0)
table_4['col_stavok_nevrolog']=col_nev_stav

table_4.head(5)

,Округ,Наименование поликлиники,Прикрепленное население на 01.08,col_priemov_nevrolog,col_stavok_nevrolog
0,Округ 1,Городская поликлиника № 17,208546,1934,7.75
1,Округ 1,Городская поликлиника № 19,232064,3190,8.00
2,Округ 1,Городская поликлиника № 31,192351,3213,9.75
3,Округ 1,Городская поликлиника № 33,218461,2630,6.50
4,Округ 1,Городская поликлиника № 35,180347,1502,7.25

In [24]:
#Добавим колонку приёмов на ставку на 01.08
table_4['приёмов на ставку'] = round(table_4['col_priemov_nevrolog']/table_4['col_stavok_nevrolog'],0)
#Добавим колонку приёмов на 10 тыс. прикреп на 01.08
table_4['приёмов на 10 тыс. прикреп'] = round((table_4['col_priemov_nevrolog']/(table_4['Прикрепленное население на 01.08']/10000))).astype('int64')
#Добавим колонку ставок на 10 тыс. прикреп на 01.08
table_4['ставок на 10 тыс. прикреп'] = round(table_4['col_stavok_nevrolog']/(table_4['Прикрепленное население на 01.08']/10000),2)

In [25]:
table_4.head(5)

,Округ,Наименование поликлиники,Прикрепленное население на 01.08,col_priemov_nevrolog,col_stavok_nevrolog,приёмов на ставку,приёмов на 10 тыс. прикреп,ставок на 10 тыс. прикреп
0,Округ 1,Городская поликлиника № 17,208546,1934,7.75,250.0,93,0.37
1,Округ 1,Городская поликлиника № 19,232064,3190,8.00,399.0,137,0.34
2,Округ 1,Городская поликлиника № 31,192351,3213,9.75,330.0,167,0.51
3,Округ 1,Городская поликлиника № 33,218461,2630,6.50,405.0,120,0.30
4,Округ 1,Городская поликлиника № 35,180347,1502,7.25,207.0,83,0.40

**ИТОГОВЫЕ НОВЫЕ 4 ТАБЛИЦЫ**

In [26]:
print('Таблица 1.1. Рейтинг округов по темпу прироста прикрепленного населения.')
table_1_1

Таблица 1.1. Рейтинг округов по темпу прироста прикрепленного населения.

,Прикрепленное население на 01.07,Прикрепленное население на 01.08,Прирост в % июль-август,Прикрепленное население на 01.09,Прирост в % август-сентябрь
Округ,,,,,
Округ 1,1374841,1376032,0.09,1378397,0.17
Округ 2,1239533,1242264,0.22,1247440,0.42
Округ 3,2574811,2578452,0.14,2585511,0.27
Округ 4,1259254,1261734,0.20,1265705,0.31
Округ 5,992555,995001,0.25,999263,0.43
Округ 6,625641,626190,0.09,628149,0.31
Округ 8,1064288,1064325,0.00,1066234,0.18
Округ 9,1377705,1379270,0.11,1381464,0.16

In [27]:
print('Таблица 1.2. Рейтинг специальностей по количеству приемов в сентябре.')
table_1_2

Таблица 1.2. Рейтинг специальностей по количеству приемов в сентябре.

                        Количество состоявшихся приемов, в т. ч. (Сентябрь)
Специальность врача
Врач-хирург                                                        186458
Врач-офтальмолог                                                   150395
Врач-оториноларинголог                                             114769
Врач-невролог                                                      112455
Врач-эндокринолог                                                  109307
Врач-уролог                                                        102119
Врач-кардиолог                                                      72523

In [28]:
print('Таблица 2. Рейтинг взрослых поликлиник по доле внеплановых приемов врачей-специалистов за сентябрь.')
table_3

Таблица 2. Рейтинг взрослых поликлиник по доле внеплановых приемов врачей-специалистов за сентябрь.

,Округ,Наименование поликлиники,"Количество состоявшихся приемов, в т. ч. (Сентябрь)",Доля внеплановых в %,Доля несост. план. %,Прикреп. 01.09,Ставок 01.09
0,Округ 1,Городская поликлиника № 17,18542,5.48,13.87,207580,57.50
1,Округ 1,Городская поликлиника № 19,23479,8.83,6.75,232820,46.25
2,Округ 1,Городская поликлиника № 31,21736,4.92,13.51,193239,53.25
3,Округ 1,Городская поликлиника № 33,20768,5.22,8.04,219393,43.25
4,Округ 1,Городская поликлиника № 35,19395,11.82,10.95,181032,41.50
5,Округ 1,Городская поликлиника № 43,15219,7.74,15.51,152132,38.75
6,Округ 2,Городская поликлиника № 22,22039,9.57,11.74,221301,62.50
7,Округ 2,Городская поликлиника № 3,22279,4.62,14.33,244098,58.00
8,Округ 2,Городская поликлиника № 37,17826,6.58,11.88,180177,45.25
9,Округ 2,Городская поликлиника № 39,16673,4.31,16.07,183615,41.25
10,Округ 2,Городская поликлиника № 47,20492,13.07,13.00,201730,46.00
11,Округ 3,Городская поликлиника № 1,15104,3.20,14.70,168298,39.50
12,Округ 3,Городская поликлиника № 10,20360,18.91,15.07,194511,40.50
13,Округ 3,Городская поликлиника № 11,17027,12.40,16.94,195526,42.50
14,Округ 3,Городская поликлиника № 20,15838,5.54,11.71,189415,44.75
15,Округ 3,Городская поликлиника № 21,12629,7.98,14.86,141296,28.73
16,Округ 3,Городская поликлиника № 23,19887,4.50,15.38,222678,45.00
17,Округ 3,Городская поликлиника № 30,18504,3.89,14.78,233775,59.25
18,Округ 3,Городская поликлиника № 38,21873,16.18,11.96,185074,50.00
19,Округ 3,Городская поликлиника № 4,14173,17.82,15.44,115423,32.50
20,Округ 3,Городская поликлиника № 45,22304,2.24,12.39,261142,53.50
21,Округ 3,Городская поликлиника № 9,29587,8.50,10.61,275440,69.75
22,Округ 4,Городская поликлиника № 12,22138,7.20,13.63,261243,59.75
23,Округ 4,Городская поликлиника № 16,21334,9.18,16.80,247422,60.50
24,Округ 4,Городская поликлиника № 42,27516,18.04,14.27,273176,60.25
25,Округ 4,Городская поликлиника № 6,31622,14.09,14.94,308125,71.25
26,Округ 5,Городская поликлиника № 14,21032,11.57,14.11,259266,52.00
27,Округ 5,Городская поликлиника № 2,29767,7.08,13.07,282970,70.50
28,Округ 5,Городская поликлиника № 24,19527,12.03,15.30,243203,74.00
29,Округ 5,Городская поликлиника № 28,1938,70.74,-0.53,23787,0.00
30,Округ 6,Городская поликлиника № 25,7420,12.13,19.46,89254,32.05
31,Округ 6,Городская поликлиника № 28,7765,10.62,17.78,81795,27.75
32,Округ 6,Городская поликлиника № 29,13696,5.18,13.99,122331,31.01
33,Округ 6,Городская поликлиника № 34,14873,5.33,13.13,152627,38.25
34,Округ 6,Городская поликлиника № 8,7026,11.29,15.67,92023,25.25
35,Округ 8,Городская поликлиника № 13,10296,8.85,15.50,99329,21.50
36,Округ 8,Городская поликлиника № 18,10933,5.10,15.41,135552,28.50
37,Округ 8,Городская поликлиника № 26,23057,3.84,9.74,179451,67.25
38,Округ 8,Городская поликлиника № 27,12019,7.61,14.53,134975,27.25
39,Округ 8,Городская поликлиника № 36,13023,1.72,13.20,160042,36.75
40,Округ 8,Городская поликлиника № 41,20490,1.69,13.93,201373,58.30
41,Округ 9,Городская поликлиника № 40,23957,6.09,13.71,269697,64.75
42,Округ 9,Городская поликлиника № 44,14528,6.97,9.25,154715,41.25
43,Округ 9,Городская поликлиника № 46,22641,2.98,14.90,309823,61.00
44,Округ 9,Городская поликлиника № 5,23804,5.81,13.37,192111,49.75
45,Округ 9,Городская поликлиника № 7,21890,4.21,13.14,242032,55.25

In [29]:
print('Таблица 3. Рейтинг взрослых поликлиник по нагрузке на ставку за август. Врач-невролог.')
table_4

Таблица 3. Рейтинг взрослых поликлиник по нагрузке на ставку за август. Врач-невролог.

,Округ,Наименование поликлиники,Прикрепленное население на 01.08,col_priemov_nevrolog,col_stavok_nevrolog,приёмов на ставку,приёмов на 10 тыс. прикреп,ставок на 10 тыс. прикреп
0,Округ 1,Городская поликлиника № 17,208546,1934,7.75,250.0,93,0.37
1,Округ 1,Городская поликлиника № 19,232064,3190,8.00,399.0,137,0.34
2,Округ 1,Городская поликлиника № 31,192351,3213,9.75,330.0,167,0.51
3,Округ 1,Городская поликлиника № 33,218461,2630,6.50,405.0,120,0.30
4,Округ 1,Городская поликлиника № 35,180347,1502,7.25,207.0,83,0.40
5,Округ 1,Городская поликлиника № 43,151958,1974,6.00,329.0,130,0.39
6,Округ 2,Городская поликлиника № 22,220197,2392,10.50,228.0,109,0.48
7,Округ 2,Городская поликлиника № 3,243486,3132,9.25,339.0,129,0.38
8,Округ 2,Городская поликлиника № 37,179351,1519,6.50,234.0,85,0.36
9,Округ 2,Городская поликлиника № 39,182661,2258,6.25,361.0,124,0.34
10,Округ 2,Городская поликлиника № 47,201093,1660,7.00,237.0,83,0.35
11,Округ 3,Городская поликлиника № 1,167788,1699,7.50,227.0,101,0.45
12,Округ 3,Городская поликлиника № 10,194094,2099,6.00,350.0,108,0.31
13,Округ 3,Городская поликлиника № 11,195226,1577,6.00,263.0,81,0.31
14,Округ 3,Городская поликлиника № 20,189027,2342,8.75,268.0,124,0.46
15,Округ 3,Городская поликлиника № 21,141077,1433,3.55,404.0,102,0.25
16,Округ 3,Городская поликлиника № 23,222054,1955,7.25,270.0,88,0.33
17,Округ 3,Городская поликлиника № 30,232799,2053,10.75,191.0,88,0.46
18,Округ 3,Городская поликлиника № 38,184499,2533,8.25,307.0,137,0.45
19,Округ 3,Городская поликлиника № 4,115143,1890,5.50,344.0,164,0.48
20,Округ 3,Городская поликлиника № 45,260657,1937,6.75,287.0,74,0.26
21,Округ 3,Городская поликлиника № 9,273996,3818,11.75,325.0,139,0.43
22,Округ 4,Городская поликлиника № 12,260460,2071,11.50,180.0,80,0.44
23,Округ 4,Городская поликлиника № 16,246521,2845,11.00,259.0,115,0.45
24,Округ 4,Городская поликлиника № 42,272255,2174,10.25,212.0,80,0.38
25,Округ 4,Городская поликлиника № 6,307206,4134,12.50,331.0,135,0.41
26,Округ 5,Городская поликлиника № 14,258305,1560,8.00,195.0,60,0.31
27,Округ 5,Городская поликлиника № 2,281789,3973,13.25,300.0,141,0.47
28,Округ 5,Городская поликлиника № 24,241961,2536,14.50,175.0,105,0.60
29,Округ 5,Городская поликлиника № 28,23788,115,0.00,inf,48,0.00
30,Округ 6,Городская поликлиника № 25,89162,478,6.50,74.0,54,0.73
31,Округ 6,Городская поликлиника № 28,81567,735,4.50,163.0,90,0.55
32,Округ 6,Городская поликлиника № 29,122119,1613,5.00,323.0,132,0.41
33,Округ 6,Городская поликлиника № 34,151961,1392,5.00,278.0,92,0.33
34,Округ 6,Городская поликлиника № 8,91844,667,3.75,178.0,73,0.41
35,Округ 8,Городская поликлиника № 13,99303,995,2.50,398.0,100,0.25
36,Округ 8,Городская поликлиника № 18,135389,930,4.00,232.0,69,0.30
37,Округ 8,Городская поликлиника № 26,178477,2439,10.25,238.0,137,0.57
38,Округ 8,Городская поликлиника № 27,134581,1558,4.00,390.0,116,0.30
39,Округ 8,Городская поликлиника № 36,159861,1783,6.00,297.0,112,0.38
40,Округ 8,Городская поликлиника № 41,201548,1837,9.75,188.0,91,0.48
41,Округ 9,Городская поликлиника № 40,271949,2405,8.25,292.0,88,0.30
42,Округ 9,Городская поликлиника № 44,154092,1393,6.75,206.0,90,0.44
43,Округ 9,Городская поликлиника № 46,307673,2548,9.75,261.0,83,0.32
44,Округ 9,Городская поликлиника № 5,191839,2577,7.75,333.0,134,0.40
45,Округ 9,Городская поликлиника № 7,241434,2602,9.25,281.0,108,0.38